### ISSUE TITLE
zln выпадает по исключению в случае, если сервер выключен

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#114]
Traceback (most recent call last):
  File "./zln/zln.py", line 26, in main
    raise RuntimeError("\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438")
RuntimeError: \u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./zln/zln.py", line 48, in <module>
    main(sys.argv)
  File "./zln/zln.py", line 45, in main
    print(exc)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

**Comment by DronMDF** [comment]
Борее свежий снапшот
```
Traceback (most recent call last):
  File "./zln/zln.py", line 26, in main
    
RuntimeError: \u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./zln/zln.py", line 48, in <module>
    rscore = XZoldScore(rremote.headers['X-Zold-Score'])
  File "./zln/zln.py", line 45, in main
    except Exception as err:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
```
